export const LANG_EN_NAME = 'en-EN';

export const LANG_EN_TRANS = {
    'ORDER_NO': 'Order No',
    'CUSTOMER': 'Customer',
    'PROBLEM_SOURCE': 'Problem Source',
    'PROBLEM_TYPE': 'Problem Type',
    'PRIORITY': 'Priority',
    'ETA': 'Estimated Arrival Time',
    'OG': 'Date To Be',
    'STATUS': 'Status',
    'NO_DATA_FOUND': 'No data found',
    'INTERNAL_PARTICIPANT': 'Internal Participant',
    'EXTERNAL_PARTICIPANT': 'External Participant',
    'TEAM': 'Team',
    'TASK_TYPE': 'Task Type',
    'SELECT_TEAM_MEMBER_INFO': 'Continue as',
    'DELAYED_ORDER': 'Delayed Order',
    'ORDER_ADDED_PROBLEM': 'Order Added Problem',
    'ORDER_ADDED_EXTRA_CHARGED': 'Order Added Extra Charged',
    'DELAYED_ORDER_UPPERCASE': 'DELAYED ORDER',
    'ORDER_ADDED_PROBLEM_UPPERCASE': 'ORDER ADDED PROBLEM',
    'ORDER_ADDED_EXTRA_CHARGED_UPPERCASE': 'ORDER ADDED EXTRA CHARGED',
    // DASHBOARD
    'DASHBOARD': 'Dashboard',
    'SERVICE_TYPE': 'Service Type',
    'COUNTRY': 'Country',
    'READY_DATE': 'Ready Date',
    'CUSTOMERS': 'Customers',
    'TASKS': 'Tasks',
    'ORDERS': 'Orders',
    'CALENDAR': 'Calendar',
    'PRIOR_ORDERS': 'Prior Orders',
    'CUSTOMER_INFO': 'Customer Info',
    'WEIGHT': 'Weight',
    'FIRST_ORDERS_IN_NEW_LOCATION': 'First Orders at New Location',
    'GENERAL_UPPARCASE': 'GENERAL',
    'ORDERS_UPPERCASE': 'ORDERS',
    'VISITS_UPPERCASE': 'VISITS',

    // CUSTOMERS
    'CUSTOMER_SEARCH': 'Search Customer',
    'CUSTOMER_SEARCH_INFO': 'You can search customer either by id or name',
    'CUSTOMER_SEARCH_INFO2': 'You can search customer by name',
    'MY_CUSTOMERS': 'My Customers',
    'LOCATION': 'Location',
    'PAST_VISITS': 'Past Visits',
    'FUTURE_VISITS': 'Future Visits',
    'DATE': 'Date',
    'INTERVIEWEE': 'Interviewee',
    'SUBJECT': 'Subject',
    'CUSTOMER_DETAIL': 'Customer Detail',
    'CUSTOMER_ID': 'Customer Id',
    'CUSTOMER_SECTOR': 'Customer Sector',
    'CUSTOMER_STATUS': 'Customer Status',
    'ADDRESS': 'Address',
    'CONTACTS': 'Contacts',
    'ADD': 'Add',
    'NAME_SURNAME': 'Name Surname',
    'ENTER_NAME': 'Enter Your Name',
    'DEPARTMENT': 'Department',
    'E_MAIL': 'E-mail',
    'EDIT': 'Edit',
    'SET_AS_ACTIVE': 'Set As Active',
    'SET_AS_DEFAULT': 'Set As Default',
    'ADD_CONTACT': 'Add Contact',
    'EDIT_CONTACT': 'Edit Contact',
    'SEGMENTS': 'Segments',
    'GENDER': 'Gender',
    'NAME': 'Name',
    'SURNAME': 'Surname',
    'TITLE': 'Title',
    'SELECT': 'SELECT',
    'SELECT_LOWERCASE': 'Select',
    'PHONE_NUMBER': 'Phone Number',
    'TYPE': 'Type',
    'USAGE': 'Usage',
    'IS_DEFAULT': 'Is Default',
    'PHONE_NUMBER_FORMAT_ERROR': 'Phone number is not valid',
    'SAVE': 'Save',
    'DELETE': 'Delete',
    'EMAIL_FORMAT_ERROR': 'E-mail is not valid',
    'CLOSE': 'Close',
    'EXP': 'Export',
    'IMP': 'Import',
    'PACKAGING_TYPE': 'Packaging Type',
    'GROSS_WEIGHT': 'Gross Weight',
    'AGREEMENTS': 'Agreements',
    'AGREEMENT_NO': 'Agreement Number',
    'AGREEMENT_TYPE': 'Agreement Type',
    'AGREEMENT_NAME': 'Agreement Name',
    'SERVICE_AREAS': 'Service Areas',
    'START_DATE': 'Start Date',
    'END_DATE': 'End Date',
    'START/END_DATE': 'Start / End Date',
    'ROAD FREIGHT': 'Road Freight',
    'SEA FREIGHT': 'Sea Freight',
    'AIR FREIGHT': 'Air Freight',
    'DOMESTIC DISTRIBUTION': 'Domestic Distribution',
    'CUSTOMS CLEARANCE': 'Customs Clearance',
    'WAREHOUSE MANAGEMENT': 'Warehouse Management',
    'BONDED WAREHOUSE': 'Bonded Warehouse',
    'RAILWAY TRANSPORTATION': 'Railway Transportation',
    'FAIR & EXHIBITION': 'Fair & Exhibition',
    'INSURANCE': 'Insurance',
    'RORO TRANSPORTATION': 'Roro Transportation',
    'FINISHED VEHICLE': 'Finished Vehicle',
    'PROJECT CARGO': 'Project Cargo',
    'CONTRACT': 'Contract',
    'PROTOCOL': 'Protocol',
    'VERBAL': 'Verbal',
    'TERMINATED': 'Terminated',
    'APPROVED': 'Approved',
    'NEW_OPPORTUNITY': 'New Opportunity',
    'OPPORTUNITY_NO': 'Opportunity Number',
    'OPPORTUNITY_NAME': 'Opportunity Name',
    'OPPORTUNITY_OWNER': 'Opportunity Owner',
    'ACCOUNT_LOCATION': 'Account Location',
    'OWNER_SUBSIDIARY': 'Owner Subsidiary',
    'SERVICE_AREA': 'Service Area',
    'CURRENCY': 'Currency',
    'EXPECTED_QUOTE_DATE': 'Expected Quote Date',
    'QUOTED_TURNOVER_PER_YEAR': 'Quoted Turnover Per Year',
    'EXPECTED_TURNOVER_PER_YEAR': 'Expected Turnover Per Year',
    'COMMITTED_TURNOVER_PER_YEAR': 'Committed Turnover Per Year',
    'RELATED_QUOTES': 'Related Quotes',
    'QUOTE_NO': 'Quote No',
    'QUOTE_NAME': 'Quote Name',
    'QUOTE_TYPE': 'Quote Type',
    'PDF_CREATED': 'PDF Created',
    'WON': 'Won',
    'PARTIAL_WON': 'Partial Won',
    'LOST': 'Lost',
    'SPOT': 'Spot',
    'LONG_TERM': 'Long Term',
    'TENDER': 'Tender',
    'FROM_COUNTRY': 'From Country',
    'FROM_POINT': 'From Point',
    'TO_COUNTRY': 'To Country',
    'TO_POINT': 'To Point',
    'FREQUENCY_TYPE': 'Frequency Type',
    'FREQUENCY': 'Frequency',
    'EXISTENCE_TYPE': 'Existence Type',
    'NEW': 'New',
    'EXISTING': 'Existing',
    'POINT': 'Point',
    'CUSTOMS_SERVICE_TYPE': 'Customs Service Type',
    'CUSTOMS_OFFICE': 'Customs Office',
    'PRODUCTS': 'Products',
    'SPOT_PDF_NOTE': 'Spot Pdf Note',
    'PREPARATION_NOTES': 'Preperation Notes',
    'ACTIVITY_REPORT': 'Activity Report',
    'MANAGER_NOTE': 'Manager Note',
    'NOTES': 'Notes',
    'SAVE_NOTE': 'Save Note',
    'SELECT_NOTE_TYPE': 'Select Note Type',
    'NOTE': 'Note',
    'UPDATE_NOTE': 'Update Note',
    'RESET': 'Reset',
    'NOTE_UPDATED_SUCCESSFULLY': 'Note Updated Successfully',
    'NOTE_SAVED_SUCCESSFULLY': 'Note Saved Successfully',
    'NOTE_DELETED_SUCCESSFULLY': 'Note Deleted Successfully',
    'ALERT': 'Alert',
    'DELETE_NOTE': 'Delete Note',
    'ACTIVITY_DETAILS': 'Activity Details',
    'DELETE_NOTE_DIALOG_MESSAGE': 'The note you selected will be deleted. Do you want to continue?',
    'PROSPECTING': 'Prospecting',
    'QUOTED': 'Quoted',
    'VALUE_PROPOSITION': 'Value Proposition',
    'REJECTED': 'Rejected',
    'WITHDRAWN': 'Withdrawn',
    'TRUCK_LOADING': 'Truck Loading',
    'SERVICE_GROUP': 'Service Group',
    'ORDER_TYPE': 'Order Type',
    'PERIOD': 'Period',
    'TOTAL_PAYWEIGHT': 'Total Payweight',
    'DRAW_GRAPH': 'Draw Graph',
    'SPOT_QUOTE': 'Spot Quote',
    'GENERAL_QUOTE': 'General Quote',
    'PW_GRAPH': 'PW Graph',
    'MONTHLY': 'Monthly',
    'WEEKLY': 'Weekly',
    'NO_AGREEMENT_DOCUMENT': 'There is no uploaded document regarding the relevant agremeent.',


    // TASK
    'MY_TASK': 'My Tasks',
    'DELAYED_ORDERS': 'Delayed Orders',
    'ORDERS_ADDED_PROBLEM': 'Problematic Orders',
    'ORDERS_ADDED_EXTRA_CHARGED': 'Orders with Extra Charge',
    'FIRST_ORDERS_AT_NEW_LOCATION': 'FIRST ORDERS AT NEW LOCATION',
    'DELAYED_ORDERS_UPPERCASE': 'DELAYED ORDERS',
    'ORDERS_ADDED_PROBLEM_UPPERCASE': 'ORDERS ADDED PROBLEM',
    'ORDERS_ADDED_EXTRA_CHARGED_UPPERCASE': 'ORDERS WITH EXTRA CHARGED',
    'FIRST_ORDERS_AT_NEW_LOCATION_UPPERCASE': 'FIRST ORDERS AT NEW LOCATION',
    'INTERLOCUTOR': 'Interlocutor',
    'DELAY_TYPE': 'Delay Type',
    'EXPLANATION': 'Explanation',
    'COST_AMOUNT': 'Cost Amount',
    'COST_REASON': 'Cost Reason',
    'COST_DATE': 'Cost Date',
    'PROBLEM_DATE': 'Problem Date',
    'Visit the {0} customer until {1} and enter the visit note after the visit.': 'Visit the {0} customer until {1} and enter the visit note after the visit.',
    '{0} customer is assigned to you. Call the customer until {1}': '{0} customer is assigned to you. Call the customer until {1}',
    'SPECIFIC_CUSTOMER_VISIT': 'Specific Customer Visit',
    'LANE_SPECIFIC_CUSTOMER_VISIT': ' Lane Specific Customer Visit',
    'CUSTOMER_SPECIFIC_WORK': 'Customer Specific Work',
    'CROSS_SELLING': 'Cross Selling',
    'SALES_LEAD_REDIRECTING': 'Sales Lead Redirecting',
    'SELECT_SUBJECT': 'Select Subject',
    'SELECT_CUSTOMER': 'Select Customer',
    'NO_RESULT': 'No Results',
    '(MANAGER)': '(M)',
    'TASK_NUMBER': 'Task Number',
    'OPEN': 'Open',
    'REOPEN': 'Reopen',
    'COMPLETE': 'Complete',
    'COMPLETED': 'Completed',
    'POSTPONE': 'Postpone',
    'POSTPONED': 'Postponed',
    'CLOSED': 'Closed',
    'CREATED_AT': 'Created At',
    'TASK_CREATED_BY': 'Task Created By',
    'TASK_OWNER': 'Task Owner',
    'TASK_SUBJECT': 'Task Subject',
    'CANCELED': 'Canceled',
    'COMPLETE_RELATED_TASK?': 'Do you want to complete the task with number {0} related to this activity?',
    'CANCEL': 'Cancel',
    'CREATED_BY': 'Created By',
    'UPDATE_TASK_TOO': 'Update Task Too',
    'ONLY_UPDATE_ACTIVITY': 'Only Update Activity',
    'RELATED_TASK_NUMBER': 'Related Task Number',
    'TASK_WILL_BE_COMPLETED?': 'Task will be completed and task creator will be informed via email. Do you wish to proceed?',
    'TASK_CANCELLED': 'Task has been cancelled.',
    'TASK_COMPLETED': 'Task has been completed.',
    'TASK_REOPENED': 'Task has been reopened.',
    'TASK_CLOSED': 'Task has been closed.',
    'TASK_POSTPONED': 'Task has been postponed. Old Deadline: {0} / New Deadline: {1}',
    'DESC_ADDED': 'Description is added',
    'ACTION_AT': 'Action At',
    'ACTION_BY': 'Action By',
    'OPERATION_DETAIL': 'Operation Detail',
    'SET_A_NEW_DEADLINE': 'Plase set a new deadline',



    // ORDERS
    'SEARCH_ORDERS': 'Search Orders',
    'SEARCH_ORDERS_INFO': 'Search By Order Id',
    'ACTIVE_ORDERS': 'Active Orders',
    'FINALIZED_ORDERS': 'Finalized Orders',
    'ORDERS_TO_LEAVE': 'Orders To Depart',
    'ORDERS_ON_THE_ROAD': 'Orders On The Road',
    'ORDERS_ON_THE_TERMINAL': 'Orders On The Terminal',
    'ARCHIVED_ORDERS': 'Archived Orders',
    'ACTIVE_ORDERS_UPPERCASE': 'ACTIVE ORDERS',
    'FINALIZED_ORDERS_UPPERCASE': 'FINALIZED ORDERS',
    'ORDERS_TO_LEAVE_UPPERCASE': 'ORDERS TO DEPART',
    'ORDERS_DEPARTED_FROM_TERMINAL': 'Orders Departed From Terminal',
    'ORDERS_ON_THE_ROAD_UPPERCASE': 'ORDERS ON THE ROAD',
    'ORDERS_ON_THE_TERMINAL_UPPERCASE': 'ORDERS ON THE TERMINAL',
    'ARCHIVED_ORDERS_UPPERCASE': 'ARCHIVED ORDERS',
    'SENDER': 'Sender',
    'LOADING_LOCATION': 'Loading Location',
    'RECIPIENT': 'Recipient',
    'DELIVERY_LOCATION': 'Delivery Location',
    'ACTIVE': 'ACTIVE',
    'Active': 'ACTIVE',
    'PASSIVE': 'PASSIVE',
    'Passive': 'PASSIVE',
    'AKTIF': 'ACTIVE',
    'Aktif': 'ACTIVE',
    'PASIF': 'PASSIVE',
    'Pasif': 'PASSIVE',
    'ORDER_DETAIL': 'Order Detail',

        // MONTHS
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December',
    'Scope': 'Scope',
    'Tool': 'Tool',
    'Add_New_Event': 'Add New Event',
    'Update_Event': 'Update Event',
    'UPDATE': 'Update',
    'Event_Type': 'Event Type',
    'Header': 'Header',
    'Location': 'Location',
    'Description': 'Description',
    'Select_Segment': 'Select Segment',
    'more': 'more',
    'SEARCH': 'Search',
    'Segment_not_found': 'No Segment was Found!',
    'Provide_header': 'Provide header',
    'Provide_event_type': 'Provide event type',
    'Provide_activity_type': 'Provide activity type',
    'Provide_segment_type': 'Provide segment type',
    'Provide_scope_type': 'Provide scope type',
    'Provide_tool_type': 'Provide tool type',
    'Provide_location': 'Provide location',
    'Provide_participant': 'Provide participant(s)',
    'Provide_account': 'Provide account',
    'PROVIDE_GENDER': 'Provide gender',
    'PROVIDE_TITLE': 'Provide title',
    'PROVIDE_NAME': 'Provide name',
    'PROVIDE_SURNAME': 'Provide surname',
    'PROVIDE_DEPARTMENT': 'Provide department',
    'Correct_Date': 'Event start date cannot be after the end date',
    'Provide_description': 'Provide description',
    'ACTIVATION_MEETING': 'Activation Meeting',
    'OPERATIONAL_PROBLEMS': 'Operational Problems',
    'GENERAL_ASSESSMENT': 'Genelal Assesment',
    'SATISFACTION_AND_COMPLAINT_MANAGEMENT': 'Satisfaction And Complaint Management',
    'SALES_QUOTE_OR_CONTRACT_NEGOTIATION': 'Sales Quote Or Contract Negotiation',
    'PRODUCT_INTRODUCTION': 'Product Introduction',
    'COLLECTION_MEETING': 'Collection Meeting',
    'LTL_CUSTOMER_ACQUISITION': 'LTL Customer Acquisition',
    'CALL': 'Call',
    'MEETING': 'Meeting',
    'INTERNAL': 'Internal',
    'EXTERNAL': 'External',
    'EVENT': 'Event',
    'CREATE_ACTIVITY': 'Create Activity',
    'Activity_Type': 'Activity Type',
    'SHARE_WITH_ALL_PARTICIPANTS': 'Share With All Participants',
    'SEE_ACTIVITY': 'See Activity',
    'UPDATE_EVENT': 'Update Event',
    'DELETE_EVENT': 'Delete Event',
    'ACTIVITY_UPDATE_ERROR': 'Please fill all the options to update the activity',
    'ACTIVITY_DELETE_SUCCESS': 'You have successfully deleted the activity',
    'ACTIVITY_UPDATE_SUCCESS': 'You have successfully updated the activity',
    'ACTIVITY_CREATE_SUCCESS': 'You have successfully created an activity',
    'ACTIVITY_CREATE_ERROR': 'Please fill all the options to create a new activity',
    'ACTIVITY_CREATE_ERROR2': 'Error occurred during creating an activity.',
    'ACTIVITY_UPDATE_ERROR2': 'Error occurred during updating the activity.',
    'EXPENSE_ORDER': 'Expense Order',
    'PROBLEMATIC_ORDER': 'Problematic Order',
    'MALE': 'Erkek',
    'FEMALE': 'Kadın',
    'COUNTRY_CODE': 'Ülke Kodu',
    'REGION_CODE': 'Bölge Kodu',
    'CREATE_CONTACT_SUCCESS_MESSAGE': 'Contact created succesfully.',
    'CREATE_CONTACT_ERROR_MESSAGE': 'An error occurred while creating the contact.',
    'EDIT_CONTACT_SUCCESS_MESSAGE': 'Contact edited succesfully.',
    'EDIT_CONTACT_ERROR_MESSAGE': 'An error occurred while editing the contact.',

    'ALL_ORDERS': 'All Orders',
    'COMPLAINTS': 'Complaints',
    'COMPLAINT_TYPE': 'Complaint Type',
    'UPDATE_COMPLAINT': 'Update Complaint',
    'COMPLAINT_DUE_DATE': 'Resolving Due Date',
    'COMPLAINT_SUBJECT': 'Complaint Subject',
    'Add_New_Complaint': 'Add New Complaint',
    'Update_New_Complaint': 'Update Complaint',
    'Provide_customer': 'Provide Customer',
    'Provide_complaint_type': 'Provide complaint type',
    'DESCRIPTION': 'Description',
    'VIDEO_CONFERENCE': 'Video Conference',
    'E MAIL': 'E-mail',
    'FAIR': 'Fair',
    'COMPLAINT_NO': 'Complaint Number',
    'COMPLAINT_CREATED_SUCCESSFULLY': 'Complaint created successfully.',
    'COMPLAINT_EDITED_SUCCESSFULLY': 'Complaint edited successfully.',
    'NEW_COMPLAINT': 'New Complaint',
    'DELETE_CONTACT_DIALOG_MESSAGE': 'The contact you selected will be deleted. Do you want to continue?',
    'DELETE_ACTIVITY_DIALOG_MESSAGE': 'The activity you selected will be deleted. Do you want to continue?',
    'YES': 'Yes',
    'DELETE_CONTACT_SUCCESS_MESSAGE': 'Selected contact has been successfully deleted',
    'DELETE_EVENT_SUCCESS_MESSAGE': 'Selected event has been successfully deleted',
    'DELETE_ACTIVITY_ERROR_MESSAGE': 'An error happened while deleting the activity',
    'DAMAGE': 'Damage',
    'MISSING': 'Missing',
    'COMPLAINT_STATUS': 'Complaint Status',
    'SOLVED': 'Solved',
    'NOT_SOLVED': 'Not Solved',
    'SOLVE_COMPLAINT': 'Şikayeti Çöz',
    'SOLVED_COMPLAINT_DESCRIPTION': 'Solved Complaint Description',
    'FINANCE': 'FINANCE',
    'BUSINESS_AREA': 'Business Area',
    'DEBIT_TOTAL': 'Debit Total',
    'DUE_EXPIRED_AMOUNT': 'Due Expired Amount',
    'DUE_WAITING_AMOUNT': 'Due Waiting Amount',
    'ORDER_NOT_FOUND': 'Order not found',
    'ORDER_CODE_REQUIRED': 'Order Code Required',
    'PROFILE': 'Profile',
    'LOG_OUT': 'Log out',
    'ACTIVITY_DELETE_ERROR': 'Selected activity cannot be deleted',
    'ACTIVITY': 'Activity',
    'UPDATE_ACTIVITY': 'Update Activity',
    'ADD_NEW_ACTIVITY': 'Add New Activity',
    'DELETE_ACTIVITY': 'Delete Activity',
    'TODOS': 'To Do List',
    'NEW_TODO': 'New To Do',
    'TODO_SUBJECT': 'To Do Subject',
    'ADD_NEW_TODO': 'Add New To Do',
    'UPDATE_TODO': 'Update To Do',
    'UPDATE_APP': 'Update App',
    'SELECTED_USER': 'Selected User',
    'TIME_PERIOD': 'Time Period',
    'SELECT_PERIOD': 'Select Period',
    'LAST_ONE_MONTH': 'Last One Month',
    'LAST_TWO_MONTHS': 'Last Two Months',
    'LAST_THREE_MONTHS': 'Last Three Months',
    'LAST_FOUR_MONTHS': 'Last Four Months',
    'LAST_FIVE_MONTHS': 'Last Five Months',
    'LAST_SIX_MONTHS': 'Last Six Months',
    'LAST_YEAR': 'Last Year',
    'LAST_TWO_YEARS': 'Last Two Years',
    'LAST_THREE_YEARS': 'Last Two Years',
    'ALL_TIME': 'All Time',
    'NO': 'No',
    'CUSTOMER_NAME': 'Customer Name',
    'SECTORS': 'Sector',
    'TO_DO': 'To Do List',
    'COMPLAINT_SEARCH_INFO': 'You can search by Customer Name, Complaint Type or Complaint Subject',
    'SEARCH_BY_SUBJECT': 'You can search by Subject',
    'DEADLINE': 'Deadline',
    'LOADING': 'Loading',
    'ACTIVITY_ERROR': 'An error occured with the selected activity',
    'NO_INTERNAL_PARTICIPANT': 'No Internal Participant was Found!',
    'SELECT_INTERNAL_PARTICIPANT': 'Select Internal Participant',
    'NO_EXTERNAL_PARTICIPANT': 'No External Participant was Found!',
    'SELECT_EXTERNAL_PARTICIPANT': 'Select External Participant',
    'SELECT_ACCOUNT': 'Select Account',
    'SELECT_USER': 'Select User',
    'SELECT_ACCOUNT_OWNER': 'Select Account Owner',
    'NO_ACCOUNT_FOUND': 'No Account was Found!',
    'NO_ACCOUNT_OWNER_FOUND': 'No Account Owner was Found!',
    'RECORD_DELETE_SUCCESS': 'The record has been deleted successfully.',
    'RECORD_CREATE_SUCCESS': 'The record has been created successfully.',
    'RECORD_EDIT_SUCCESS': 'The record has been edited successfully.',
    'NO_USER_FOUND': 'No User was Found!',
    'ORDER_SEARCH_INFO': 'You can search by Order No or Customer Name.',
    '404_ERROR': '404 Page Not Found',
    'PAGE_NOT_FOUND_ERROR': 'The page you were looking for does not exist',
    'TAKE_ME_HOME': 'Take me home',
    'ACCOUNTS_NOT_FOUND_WARNING': 'No customers connected to this account.',
    'PROBLEM_DETAIL': 'Problem Detail',
    'SEARCH_INPUT_PLACE_HOLDER': 'Search',
    'CREATE_DATE': 'Create Date',
    'NOTIFICATIONS': 'Notifications',
    'MARK_ALL_AS_READ': 'Mark All As Read',
    'VIEW_NOTIFICATIONS': 'View All Notifications',
    'NO_NOTIFICATIONS': 'You don\'t have any notification.',
    'DOCUMENTS': 'Documents',
    'DOCUMENTS_ON_PORTEKOL': 'You can access the current documents on Portekol via <a target="_blank" href="https://drive.google.com/drive/folders/1bDr75WXF9KsxFXOsBTi9XfNE52QMZKYI">link</a>.',
    'REQUIRED': 'Required',
    '3_OR_MORE_CHARS': 'Please enter at least 3 characters',
    'ATTACHMENTS': 'Attachments',
    'ATTACHMENT': 'Attachment',
};
