export const LANG_TR_NAME = 'tr-TR';

export const LANG_TR_TRANS = {
    'ORDER_NO': 'Sipariş No',
    'CUSTOMER': 'Müşteri',
    'PROBLEM_SOURCE': 'Problem Kaynağı',
    'PROBLEM_TYPE': 'Problem Türü',
    'PRIORITY': 'Öncelik',
    'ETA': 'Tahmini Varış Zamanı',
    'OG': 'Olması Gereken Zaman',
    'STATUS': 'Durum',
    'NO_DATA_FOUND': 'Veri bulunamadı',
    'INTERNAL_PARTICIPANT': 'İç Katılımcı',
    'EXTERNAL_PARTICIPANT': 'Dış Katılımcı',
    'TEAM': 'Takım',
    'SELECT_TEAM_MEMBER_INFO': 'olarak devam et',
    'TASK_TYPE': 'Görev Tipi',
    'DELAYED_ORDER': 'Geciken Sipariş',
    'ORDER_ADDED_PROBLEM': 'Problem Girilen Sipariş',
    'ORDER_ADDED_EXTRA_CHARGED': 'Ekstra Masraf Girilen Sipariş',
    'DELAYED_ORDER_UPPERCASE': 'GECİKEN SİPARİŞ',
    'ORDER_ADDED_PROBLEM_UPPERCASE': 'PROBLEM GİRİLEN SİPARİŞ',
    'ORDER_ADDED_EXTRA_CHARGED_UPPERCASE': 'EKSTRA MASRAF GİRİLEN SİPARİŞ',
    'CUSTOMER_INFO': 'Müşteri Bilgisi',
    'FIRST_ORDERS_IN_NEW_LOCATION': 'Yeni Lokasyonda İlk Siparişler',
    'ABC {0}' : 'ZXC {0}',

    // DASHBOARD
    'DASHBOARD': 'Dashboard',
    'SERVICE_TYPE': 'Servis Tipi',
    'COUNTRY': 'Ülke',
    'READY_DATE': 'Hazır Tarih',
    'CUSTOMERS': 'Müşterilerim',
    'TASKS': 'Görevlerim',
    'ORDERS': 'Siparişlerim',
    'CALENDAR': 'Takvim',
    'PRIOR_ORDERS': 'Öncelikli Görevlerim',
    'GENERAL_UPPARCASE': 'GENEL',
    'ORDERS_UPPERCASE': 'SİPARİŞLER',
    'VISITS_UPPERCASE': 'ZİYARETLER',

    // CUSTOMERS
    'CUSTOMER_SEARCH': 'Müşteri Arama',
    'CUSTOMER_SEARCH_INFO': 'Müşteri No ve Müşteri Adı ile arama yapabilirsiniz',
    'CUSTOMER_SEARCH_INFO2': 'Müşteri Adı ile arama yapabilirsiniz',
    'MY_CUSTOMERS': 'Bağlı Olan Müşterilerim',
    'LOCATION': 'Lokasyon',
    'PAST_VISITS': 'Geçmiş Ziyaretler',
    'FUTURE_VISITS': 'Gelecek Ziyaretler',
    'DATE': 'Tarih',
    'INTERVIEWEE': 'Görüşülen Kişi',
    'SUBJECT': 'Konu',
    'CUSTOMER_DETAIL': 'Müşteri Detayı',
    'CUSTOMER_ID': 'Müşteri No',
    'CUSTOMER_SECTOR': 'Müşteri Sektörü',
    'CUSTOMER_STATUS': 'Müşteri Statüsü',
    'ADDRESS': 'Adres',
    'CONTACTS': 'Yetkililer',
    'ADD': 'Ekle',
    'NAME_SURNAME': 'Ad Soyad',
    'DEPARTMENT': 'Departman',
    'E_MAIL': 'E-mail',
    'EDIT': 'Düzenle',
    'SET_AS_ACTIVE': 'Aktif Olarak Ayarla',
    'SET_AS_DEFAULT': 'Varsayılan Olarak Ayarla',
    'ADD_CONTACT': 'Yetkili Ekle',
    'EDIT_CONTACT': 'Yetkili Düzenle',
    'SEGMENTS': 'Segmentler',
    'GENDER': 'Cinsiyet',
    'NAME': 'Ad',
    'SURNAME': 'Soyad',
    'TITLE': 'Ünvan',
    'SELECT': 'Seçiniz',
    'SELECT_LOWERCASE': 'Seçiniz',
    'PHONE_NUMBER': 'Telefon',
    'TYPE': 'Tipi',
    'USAGE': 'Kullanım Tipi',
    'IS_DEFAULT': 'Varsayılan',
    'PHONE_NUMBER_FORMAT_ERROR': 'Telefon numarası geçerli değil',
    'SAVE': 'Kaydet',
    'DELETE': 'Sil',
    'EMAIL_FORMAT_ERROR': 'E-mail geçerli değil',
    'CLOSE': 'Kapat',
    'EXP': 'İthalat',
    'IMP': 'İhracat',
    'AGREEMENTS': 'Sözleşmeler',
    'AGREEMENT_NO': 'Sözleşme Numarası',
    'AGREEMENT_TYPE': 'Sözleşme Tipi',
    'AGREEMENT_NAME': 'Sözleşme Adı',
    'SERVICE_AREAS': 'Hizmet Alanları',
    'START_DATE': 'Başlangıç Tarihi',
    'END_DATE': 'Bitiş Tarihi',
    'START/END_DATE': 'Başlangıç / Bitiş Tarihi',
    'ROAD FREIGHT': 'Kara Taşımacılığı',
    'SEA FREIGHT': 'Deniz Taşımacılığı',
    'AIR FREIGHT': 'Hava Taşımacılığı',
    'DOMESTIC DISTRIBUTION': 'Yurtiçi Dağıtım',
    'CUSTOMS CLEARANCE': 'Gümrükleme',
    'WAREHOUSE MANAGEMENT': 'Depo Yönetimi',
    'BONDED WAREHOUSE': 'Antrepo',
    'RAILWAY TRANSPORTATION': 'Raylı Taşıma',
    'FAIR & EXHIBITION': 'Fuar',
    'INSURANCE': 'Sigorta',
    'RORO TRANSPORTATION': 'Roro Taşımacılığı',
    'FINISHED VEHICLE': 'Bitmiş Araç',
    'PROJECT CARGO': 'Proje Kargo',
    'CONTRACT': 'Kontrat',
    'PROTOCOL': 'Protocol',
    'VERBAL': 'Sözlü',
    'TERMINATED': 'Sonlandırıldı',
    'APPROVED': 'Onaylandı',
    'NEW_OPPORTUNITY': 'Yeni Fırsat',
    'OPPORTUNITY_NO': 'Fırsat Numarası',
    'OPPORTUNITY_NAME': 'Fırsat İsmi',
    'OPPORTUNITY_OWNER': 'Fırsat Sahibi',
    'ACCOUNT_LOCATION': 'Hesap Lokasyonu',
    'OWNER_SUBSIDIARY': 'Teklif Sahibi Şube',
    'SERVICE_AREA': 'Hizmet Alanı',
    'EXPECTED_QUOTE_DATE': 'Beklenen Teklif Tarihi',
    'QUOTED_TURNOVER_PER_YEAR': 'Yıllık Teklif Geliri',
    'EXPECTED_TURNOVER_PER_YEAR': 'Beklenen Yıllık Gelir',
    'COMMITTED_TURNOVER_PER_YEAR': 'Kazanılan Yıllık Teklif Geliri',
    'RELATED_QUOTES': 'İlişkili Teklifler',
    'QUOTE_NO': 'Teklif Numarası',
    'QUOTE_NAME': 'Teklif Adı',
    'QUOTE_TYPE': 'Teklif Tipi',
    'PDF_CREATED': 'PDF Oluşturuldu',
    'PARTIAL_WON': 'Kısmi Kazanıldı',
    'SPOT': 'Spot',
    'LONG_TERM': 'Uzun Dönem',
    'TENDER': 'İhale',
    'FROM_COUNTRY': 'Çıkış Ülkesi',
    'FROM_POINT': 'Çıkış Noktası',
    'TO_COUNTRY': 'Varış Ülkesi',
    'TO_POINT': 'Varış Noktası',
    'FREQUENCY_TYPE': 'Sıklık Tipi',
    'EXISTENCE_TYPE': 'Yeni/Mevcut',
    'NEW': 'Yeni',
    'EXISTING': 'Mevcut',
    'POINT': 'Nokta',
    'CUSTOMS_SERVICE_TYPE': 'Gümrük Hizmet Tipi',
    'CUSTOMS_OFFICE': 'Gümrük Ofisi',
    'PRODUCTS': 'Ürünler',
    'Turkey': 'Türkiye',
    'Germany': 'Almanya',
    'Italy': 'İtalya',
    'France': 'Fransa',
    'United Kingdom': 'İngiltere',
    'Spain': 'İspanya',
    'Netherlands': 'Hollanda',
    'Poland': 'Polonya',
    'Belgium': 'Belçika',
    'Czech Republic': 'Çek Cumhuriyeti',
    'Austria': 'Avusturya',
    'Australia': 'Avustralya',
    'Bulgaria': 'Bulgaristan',
    'Romania': 'Romanya',
    'PROSPECTING': 'Çalışılıyor',
    'QUOTED': 'Teklif Verildi',
    'VALUE_PROPOSITION': 'Fiyat Çalışması Yapılıyor',
    'REJECTED': 'Reddedildi',
    'WITHDRAWN': 'Vazgeçildi',
    'TRUCK_LOADING': 'Araç Doluluğu',
    'SERVICE_GROUP': 'Servis Grubu',
    'ORDER_TYPE': 'Sipariş Tipi',
    'PERIOD': 'Periyot',
    'TOTAL_PAYWEIGHT': 'Toplam Payweight',
    'DRAW_GRAPH': 'Grafiği Çiz',
    'SPOT_QUOTE': 'Spot Teklif',
    'GENERAL_QUOTE': 'Genel Teklif',
    'PW_GRAPH': 'PW Grafiği',
    'NO_AGREEMENT_DOCUMENT': 'İlgili sözleşmeye dair yüklenmiş doküman bulunmamaktadır.',


    // TASK
    'MY_TASK': 'Görevlerim',
    'DELAYED_ORDERS': 'Geciken Siparişler',
    'ORDERS_ADDED_PROBLEM': 'Problem Girilen Siparişler',
    'ORDERS_ADDED_EXTRA_CHARGED': 'Ekstra Masraf Girilen Siparişler',
    'FIRST_ORDERS_AT_NEW_LOCATION': 'Yeni Lokasyondan İlk Siparişler',
    'DELAYED_ORDERS_UPPERCASE': 'GECİKEN SİPARİŞLER',
    'ORDERS_ADDED_PROBLEM_UPPERCASE': 'PROBLEM GİRİLEN SİPARİŞLER',
    'ORDERS_ADDED_EXTRA_CHARGED_UPPERCASE': 'EKSTRA MASRAF GİRİLEN SİPARİŞLER',
    'FIRST_ORDERS_AT_NEW_LOCATION_UPPERCASE': 'YENİ LOKASYONDAN İLK SİPARİŞLER',
    'INTERLOCUTOR': 'Muhatap',
    'DELAY_TYPE': 'Gecikme Tipi',
    'EXPLANATION': 'Açıklama',
    'COST_AMOUNT': 'Masraf Tutarı',
    'COST_REASON': 'Masraf Sebebi',
    'COST_DATE': 'Masraf Tarihi',
    'PROBLEM_DATE': 'Problem Tarihi',
    'TODOS': 'Yapılacaklar',
    'NEW_TODO': 'Yeni Ekle',
    'TODO_SUBJECT': 'Konu',
    'ADD_NEW_TODO': 'Yeni Ekle',
    'Visit the {0} customer until {1} and enter the visit note after the visit.': '{0} müşterisini {1} tarihine kadar ziyaret ediniz ve ziyaret sonrasında ziyaret notunu giriniz.',
    '{0} customer is assigned to you. Call the customer until {1}': '{0} müşterisi size tanımlanmıştır. {1} tarihine kadar müşteriyi arayınız.',
    'SPECIFIC_CUSTOMER_VISIT': 'Spesifik Müşteri Ziyareti',
    'LANE_SPECIFIC_CUSTOMER_VISIT': 'Lane Spesifik Müşteri Ziyareti',
    'CUSTOMER_SPECIFIC_WORK': 'Müşteri Spesifik Çalışması',
    'CROSS_SELLING': 'Cross Selling',
    'SALES_LEAD_REDIRECTING': 'Sales Lead Yönlendirilmesi',
    'SELECT_SUBJECT': 'Konu Seçiniz',
    'SELECT_CUSTOMER': 'Müşteri Seçiniz',
    'NO_RESULT': 'Sonuç yok',
    '(MANAGER)': '(Y)',
    'TASK_NUMBER': 'Task Numarası',
    'REOPEN': 'Tekrar Aç',
    'COMPLETE': 'Tamamla',
    'COMPLETED': 'Tamamlandı',
    'POSTPONE': 'Ertele',
    'POSTPONED': 'Ertelendi',
    'CREATED_AT': 'Açılma Tarihi',
    'TASK_CREATED_BY': 'Taskı Açan',
    'TASK_OWNER': 'Task Sahibi',
    'TASK_SUBJECT': 'Task Konusu',
    'CREATED_BY': 'Oluşturan',
    'COMPLETE_RELATED_TASK?': 'Aktiviteye bağlı {0} numaralı taskı da tamamlandı statüsüne çekmek istiyor musunuz?',
    'UPDATE_TASK_TOO': 'Taskı da Güncelle',
    'ONLY_UPDATE_ACTIVITY': 'Sadece Aktiviteyi Güncelle',
    'RELATED_TASK_NUMBER': 'İlgili Task Numarası',
    'TASK_WILL_BE_COMPLETED?': 'Task tamamlanmış olarak kapatılacak ve taskı açan kişiye tamamlandı bilgisi gidecektir. Devam etmek istiyor musunuz?',
    'TASK_CANCELLED': 'Görev iptal edildi.',
    'TASK_COMPLETED': 'Görev tamamlandı.',
    'TASK_REOPENED': 'Görev yeniden açıldı.',
    'TASK_CLOSED': 'Görev kapatıldı.',
    'TASK_POSTPONED': 'Görev ertelendi. Eski Deadline: {0} / Yeni Deadline: {1}',
    'DESC_ADDED': 'Açıklama eklendi',
    'ACTION_AT': 'Aksiyon Tarihi',
    'ACTION_BY': 'Aksiyon Alan',
    'OPERATION_DETAIL': 'İşlem Detayı',
    'SET_A_NEW_DEADLINE': 'Lütfen tamamlanması gereken tarihi giriniz',
    'SPOT_PDF_NOTE': 'Spot Pdf Notu',
    'PREPARATION_NOTES': 'Hazırlık Notları',
    'ACTIVITY_REPORT': 'Faaliyet Raporu',
    'MANAGER_NOTE': 'Yönetici Notu',
    'SAVE_NOTE': 'Notu Kaydet',
    'SELECT_NOTE_TYPE': 'Not Tipi Seçiniz',
    'UPDATE_NOTE': 'Notu Güncelle',
    'RESET': 'Sıfırla',
    'NOTE_UPDATED_SUCCESSFULLY': 'Not Başarıyla Güncellendi',
    'NOTE_SAVED_SUCCESSFULLY': 'Not Başarıyla Kaydedildi',
    'NOTE_DELETED_SUCCESSFULLY': 'Not Başarıyla Silindi',
    'ALERT': 'Uyarı',
    'DELETE_NOTE': 'Notu Sil',
    'ACTIVITY_DETAILS': 'Aktivite Detayları',
    'DELETE_NOTE_DIALOG_MESSAGE': 'Seçilen not silinecektir. Devam etmek istediğinize emin misiniz?',


    // ORDERS
    'SEARCH_ORDERS': 'Sipariş Arama',
    'SEARCH_ORDERS_INFO': 'Sipariş No ile arama yapabilirsiniz',
    'ACTIVE_ORDERS': 'Aktif Siparişlerim',
    'FINALIZED_ORDERS': 'Kesin Siparişlerim',
    'ORDERS_TO_LEAVE': 'Yola Çıkacak Siparişlerim',
    'ORDERS_ON_THE_ROAD': 'Yoldaki Siparişlerim',
    'ORDERS_ON_THE_TERMINAL': 'Terminaldeki Siparişlerim',
    'ARCHIVED_ORDERS': 'Arşivdeki Siparişlerim',
    'ACTIVE_ORDERS_UPPERCASE': 'AKTİF SİPARİŞLERİM',
    'FINALIZED_ORDERS_UPPERCASE': 'KESİN SİPARİŞLERİM',
    'ORDERS_TO_LEAVE_UPPERCASE': 'YOLA ÇIKACAK SİPARİŞLERİM',
    'ORDERS_ON_THE_ROAD_UPPERCASE': 'YOLDAKİ SİPARİŞLERİM',
    'ORDERS_ON_THE_TERMINAL_UPPERCASE': 'TERMİNALDEKİ SİPARİŞLERİM',
    'ARCHIVED_ORDERS_UPPERCASE': 'ARŞİVDEKİ SİPARİŞLERİM',
    'SENDER': 'Gönderici',
    'LOADING_LOCATION': 'Yükleme Yeri',
    'RECIPIENT': 'Alıcı',
    'DELIVERY_LOCATION': 'Teslim Yeri',
    'PACKAGING_TYPE': 'Paketleme Tipi',
    'GROSS_WEIGHT': 'Brüt Ağırlık',

    'TO': 'Kime',
    'SANITARY SYSTEM AND SPARE PARTS': 'Sıhhi Tesisat ve Yedek Parça',
    'PRODUCT DETAIL': 'Ürün Özelliği',
    'ELECTRICAL APPLIANCES': 'Elektrikli Ev Aletleri',
    'CHANGES': 'Değişiklikler',
    'HEATING & COOLING MACHINES': 'Isıtma ve Soğutma Makineleri',
    'ATA CARNET': 'Ata Karneli',
    'SELECT ALL': 'Hepsini Seç',
    'ELECTRONIC RIG': 'Elektronik Teçhizat',
    'DELIVERY COST - DOT': 'Teslimat Ücreti - DOT',
    'AT DELIVERY LOCATION': 'Teslim Lokasyonunda',
    'DAILY': 'Günlük',
    'PHILIPPINES': 'FİLİPİNLER',
    'PRODUCTION PLANNING': 'Üretim Planlama',
    'INFORMATION TECHNOLOGIES': 'Bilgi Teknolojileri',
    'PRESS AND PUBLICATION': 'Basın ve Yayın',
    'MAURITIUS': 'MAURİTİUS',
    'NEW SECTOR': 'YENİ SEKTÖR',
    'PREVİOUS': 'ÖNCEKİ',
    'EKOL CROSS DOCK': 'Ekol Depo',
    'CRM INFO': 'CRM Bilgisi',
    'SALES CONTACTS': 'Satış Yetkilileri',
    'PURCHASING': 'Satın Alma',
    'CONSUMER ELECTRONICS': 'Tüketici Elektroniği',
    'LOADING ADDRESS': 'Yükleme Adresi',
    'TECHNOMARKETS': 'Teknomarket',
    'VEHICLE COUNT': 'Araç Sayısı',
    'E-COMMERCE': 'E-Ticaret',
    'AUTOMATION CONTROL': 'Otomasyon Kontrolü',
    'NO-SUBSECTOR': 'Alt Sektör Bilinmiyor',
    'COMMON INFO': 'Genel Bilgi',
    'CREATED BY': 'Oluşturan',
    'INACTIVATE': 'İnaktif Et',
    'LIGHT YÜK': 'Hafif Yük',
    'EXTERNAL': 'Dış',
    'QUOTE NAME': 'Teklif Adı',
    'LOST': 'Kaybedildi',
    'WEIGHT(KG)': 'Ağırlık(kg)',
    'WORK': 'İş',
    'SANITARY SYSTEMS AND SPARE PARTS': 'Su Sistemleri ve Yedek Parçaları',
    'NEXT': 'Sonraki',
    'OPERATION START DATE': 'Operasyon Başlangıç Tarihi',
    'BOBBIN': 'Bobin',
    'WON': 'Kazanıldı',
    'LATE ANSWER': 'Geç cevap',
    'SPECIALIST': 'Uzman',
    'SEMI-FINISHED PRODUCTS': 'Yarı Mamul Ürünler',
    'SPAREPARTS (MANUFACTURING INDUSTRY)': 'Yedek Parçalar (İmalat Sanayi)',
    'ACCOUNTS': 'Hesaplar',
    'DOMESTIC': 'İç Taşıma',
    'BAG': 'Çanta',
    'ITALIAN': 'İTALYANCA',
    'PACKAGING': 'Paketleme',
    'MARKETİNG': 'Pazarlama',
    'VOLUME': 'Hacim',
    'FREIGHT': 'Navlun',
    'BANK': 'Banka',
    'CREATED BY / CREATED DATE': 'Oluşturan / Oluşturma Tarihi',
    'ROAD': 'Kara',
    'CREATE DATE': 'Oluşturma Tarihi',
    'MARKETING': 'Pazarlama',
    'ASST. GENERAL MANAGER/DİRECTOR': 'Genel Müdür Yardımcısı',
    'CUSTOMER SERVICES': 'Müşteri Hizmetleri',
    'INTERNAL': 'İç',
    'MIN UPDATE DATE': 'Min Güncelleme Tarihi',
    'MALI': 'MALİ',
    'DELIVERY ADRESS': 'Teslim Adresi',
    'MAINTENANCE SERVICES': 'Bakım Hizmetleri',
    'SERVICE AREAS': 'Hizmet Alanları',
    'CURTAIN SIDER': 'Tenteli Araç',
    'QUOTE DETAILS': 'Teklif Detayları',
    'DOUBLE-DECK  EQUIPMENT': 'Çift ​Kat Ekipmanı',
    'ACTIVATION_MEETING': 'Devreye Alma Toplantısı',
    'CLEAR': 'TEMİZLE',
    'DANGEROUS/ADR GOODS': 'Tehlikeli/ADR Yük',
    'NEW TASKS': 'Yeni Görevler',
    'IBC CONTAINER': 'IBC Konteyner',
    'CHEQUE': 'Çek',
    'CZECH REPUBLIC': 'Çek Cumhuriyeti',
    'MARK AS CLOSE': 'Teklifi Kapat',
    'DOMESTIC TRANSPORT': 'İç Taşıma',
    'SALES': 'SATIŞ',
    'FINANCE': 'Finans',
    'COMPETITOR COMPANY': 'Rakip Firma',
    'TRAILER TYPE': 'Treyler Tipi',
    'MACHINE SUPPLY INDUSTRY': 'Makine Tedarik Sanayi',
    'NEW QUOTE': 'Yeni Teklif',
    'VOLUME(CM)': 'Hacim',
    'CALCULATED VOLUME': 'Hesaplanan Hacim',
    'FAILURE TO VEHICLE ALLOCATION': 'Araç Tahsis Edilememesi',
    'HEIGHT(CM)': 'Yükseklik(cm)',
    'SERVICE DETAILS': 'Servis Özellikleri',
    'NOTE': 'Not',
    'NIGERIA': 'NİJERYA',
    'FOREIGN TRADE': 'Dış Ticaret',
    'PREVIOUS PAGE': 'ÖNCEKİ',
    'MARBLE': 'Mermer',
    'AUSTRALIA': 'AVUSTRALYA',
    'EDIT ACCOUNT': 'Hesabı Düzenle',
    'PHONE': 'Telefon',
    'DEAR': 'Sayın',
    'HEALTH CERTIFICATION': 'Sağlık Sertifikası',
    'SECTORS': 'Sektör',
    'MARSHALL ISLANDS': 'MARŞAL ADALARI',
    'SECURITY SENSOR': 'Güvenlik Sensörlü',
    'LETTER OF GUARANTEE': 'Teminat Mektubu',
    'AUTOMOTIVE': 'Otomotiv',
    'HH:MM': 'ss:dd',
    'TURKEY': 'Türkiye',
    'NOTE TYPE': 'Not Tipi',
    'NO STANDARD VEHICLE': 'Standart Araç Yok',
    'CONSTRUCTION & DECORATION': 'İnşaat ve Dekorasyon',
    'PALLET': 'Palet',
    'SPAİN': 'İSPANYA',
    'FOOD - FRESH / DAILY FOOD': 'Taze Yemek  / Günlük Yemek',
    'CONTACT INFORMATION': 'Yetkili Bilgisi',
    'LOST REASON': 'Kaybedilme Nedeni',
    'LINKEDIN PROFILES': 'Linkedin Profili',
    'DOCUMENTS': 'Belgeler',
    'GITTER BOX': 'Kafes',
    'ADMINISTRATIVE': 'İDARİ',
    'EDIT CONTACT': 'Yetkili Düzenleme',
    'NEW CALEDONIA': 'YENİ KALEDONYA',
    'PERSONAL': 'Şahsi',
    'WIDTH': 'En',
    'EXTRA SERVICES': 'Ekstra Servisler',
    'HEAVY LOAD': 'Ağır Yük',
    'TRUCK İNDUSTRY': 'Kamyon Sanayi',
    'SET AS ACTIVE': 'Aktif Olarak Belirle',
    'PAYMENT TERMS': 'Ödeme Kuralları',
    'SEARCH IN ONEORDER': 'OneOrder\'da Ara',
    'QUOTE DETAİLS': 'Teklif Özellikleri',
    'NIUE': 'NİUE',
    'DEFENSE INDUSTRY': 'Savunma Sanayii',
    'WAREHOUSE PRICE': 'Depo Ücreti',
    'INACTIVATE PERMANENETLY': 'Kalıcı Olarak İnaktif Et',
    'SMOKING AND TOBACCO': 'Sigara ve Tütün',
    'BUSINESS DEVELOPMENT': 'İş Geliştirme',
    'SPOT QUOTE': 'Spot Teklif',
    'INACTIVATE UNTIL A SPECIFIC TIME': 'Belirli Zamana Kadar İnaktif Et',
    'CRM & SALES CONTACTS': 'CRM & Satış Yekili Kişiler',
    'ACCOUNT': 'Hesap',
    'SELECT A DOCUMENT BELOW AND THIS FIELD WILL BE AUTOMATICALLY FILLED.': 'Aşağıdan bir belge seçin ve bu alan otomatik olarak doldurulacaktır.',
    'DELİVERY COST': 'Teslim Maliyeti',
    'NEW COMPANY': 'YENİ FİRMA',
    'DELIVERY COST PRICE': 'Teslimat Ücreti',
    'OK': 'TAMAM',
    'COMPLETED TASKS': 'TAMAMLANMIŞ GÖREVLER',
    'CONTACT': 'Yetkili',
    'TOTAL ACCOUNTS': 'Toplam Hesaplar',
    'PLASTIC RAW MATERIALS': 'Plastik Hammaddeler',
    'TOTAL OPEN LONG TERM QUOTES': 'Toplam Açık Uzun Dönem Teklifler',
    'ARRIVAL': 'Varış',
    'MIN. DEGREE': 'Min. Derece',
    'MOBILE': 'Cep telefonu',
    'COMPANY': 'Firma',
    'SEARCH FOR ACCOUNT...': 'Hesap ara...',
    'MAX UPDATE DATE': 'Maks Güncelleme Tarihi',
    'LIBYA': 'LİBYA',
    'ASST. SPECIALIST': 'Uzman Yardımcısı',
    'PALLETIZATION': 'Paletleme',
    'TECHNOLOGY PRODUCTS': 'Teknoloji Ürünleri',
    'LOGISTICS': 'Lojistik',
    'CHANGED BY': 'Değiştiren ',
    'FREE ZONE': 'Serbest Bölge',
    'TOURISM': 'Turizm',
    'EMAİLS': 'Email',
    'HEALTH & PERSONAL CARE': 'Sağlık ve Kişisel Bakım',
    'SPAREPARTS ( MANUFACTURING INDUSTRY)': 'İmalat Sanayi Yedek Parça',
    'VEHICLE TYPE': 'Araç Tipi',
    'CRM İNFO': 'CRM Bilgi',
    'WEİGHT': 'Ağırlık',
    'CUSTOMS WAREHOUSE': 'Ambar',
    'NEW POTENTIAL': 'Yeni Potansiyel',
    'SERVİCE AREA': 'Servis Tipi',
    'PORT ADDRESS': 'Liman Adresi',
    'NO DATA...': 'Veri bulunamadı...',
    'MINIMUM AMOUNT': 'Minimum Tutar',
    'TYRES / WHEELS': 'Lastikler / Tekerlekler',
    'SPOT QUOTE CANNOT BE UPDATED UNTIL QUOTE TRANSFER TO QUADRO IS FINISHED': 'Spot teklif, Quadro\'ya teklif aktarımı tamamlanana kadar güncellenemez',
    'NO SPECIAL VEHICLE AND EQUIPMENT (SPEEDY)': 'Özel Araç ve Ekipman Yok (Hızlı)',
    'BOOK STORE': 'Kitapevi',
    'DELETE ALL': 'Hepsini Sil',
    'CLEAR ': 'TEMİZLE',
    'SPAIN': 'İspanya',
    'PRICE': 'Fiyat',
    'WIDTH CANNOT BE GREATER THAN LENGTH.': 'En boydan büyük olamaz.',
    'FRAGILE/VALUABLE GOODS': 'Kırılabilir/Değerli Yük',
    'NUTRIENTS': 'Besinler',
    'PHONE NUMBERS': 'Telefon Numaraları',
    'WEIGHT': 'Ağırlık',
    'SPARE PART': 'Yedek parça',
    'NIGER': 'NİJER',
    'QUANTITY, UNIT, SIZE, STACKING': 'Miktar, birim, boyut, istifleme',
    'MY HOME PAGE': 'Anasayfa',
    'ADD TO FREİGHT PRİCE': 'Navluna Ekle',
    'HUNGARY': 'Macaristan',
    'NICARAGUA': 'NİKARAGUA',
    'ROLL': 'Rulo',
    'BOARD MEMBER': 'Kurul Üyesi',
    'TEXTILE': 'Tekstil',
    'IN PROGRESS TASKS': 'İŞLEMDEKİ GÖREVLER',
    'ENERGY': 'Enerji',
    'CALCULATED AMOUNT': 'Hesaplanmış Tutar',
    'CONSTRUCTION & AGRICULTURAL MACHINENERY': 'İnşaat ve Tarım Makineleri',
    'SEARCH': 'ARA',
    'PAYMENT TYPE': 'Ödeme Tipi',
    'GENERAL INFO': 'Genel Bilgi',
    'LOAD TYPE': 'Yük Tipi',
    'DISCOUNTS': 'İndirimler',
    'PROPERTIES': 'Özellikler',
    'PAYMENT RULES': 'Ödeme Kuralları',
    'EXTERNAL BONDED WAREHOUSE': 'Harici Antrepo',
    'CLOSE DATE': 'Kapanış Tarihi',
    'EXIT CUSTOMS COST': 'Çıkış Gümrük Ücreti',
    'LONG GOODS': 'Uzun Yük',
    'PLEASE WAIT...': 'Lütfen Bekleyiniz...',
    'HOME TEXTILE INDUSTRY': 'Ev Tekstili Endüstrisi',
    'NEW/EXISTING': 'Yeni/Mevcut',
    'NOT_STACKABLE': 'İSTİFLENEMEZ',
    'MİN START DATE': 'Min Başlama Tarihi',
    'MALDIVES': 'MALDİVLER',
    'INVOICE COMPANY': 'Fatura Firması',
    'QUOTE SEARCH': 'Teklif Arama',
    'THIS VALUE IS REQUIRED.': 'Bu değer gereklidir.',
    'AIR': 'Hava',
    'EDIT QUOTE': 'Teklifi Düzenle',
    'CREATE PDF': 'PDF Oluştur',
    'ACCOUNTİNG': 'Muhasebe',
    'FIRST NAME': 'Adı',
    'ADD TO FREIGHT PRICE': 'Navluna Ekle',
    'SECTOR INFORMATİON': 'Sektör Bilgisi',
    'MONTHLY': 'Aylık',
    'NEPAL': 'NEPAL',
    'SLIDING ROOF': 'Sürgülü Tavan',
    'AEROSPACE INDUSTRIES': 'Havacılık ve Uzay Sanayii',
    'NORFOLK ISLAND': 'NORFOLK ADASI',
    'MAX. DEGREE': 'Maks. Derece',
    'SAVED': 'Kaydedildi',
    'ACCOUNTING': 'Muhasebe',
    'TEXTILE RETAILING': 'Hazır Giyim Perakendeciliği',
    'ARRIVAL CUSTOMS AREA DIFFERENCE': 'Varış Gümrük Alanı Farklılığı',
    'OPEN': 'Açık',
    'OPERATIONAL_PROBLEMS': 'Operasyonel Problemler',
    'NO ANSWER FROM CUSTOMER': 'Müşteriden Cevap Yok',
    'RELATED ACCOUNT': 'İlgili Hesap',
    'BODY': 'İçerik',
    'SHIP INDUSTRY': 'Gemi Sanayii',
    'E-COMMERCE (SELL THE DIFFERENT TYPE OF PRODUCT)': 'Yatay E-Ticaret Siteleri',
    'PREVIOUS': 'ÖNCEKİ',
    'SHİPMENT LOADİNG TYPE': 'FTL/LTL',
    'YOUR CONTACT': 'Yetkili',
    'LOAD DETAILS': 'Yük Özellikleri',
    'INFORMATICS': 'Bilişim',
    'VOLUME(M3)': 'Hacim(m3)',
    'SPOT QUOTE EMAIL': 'Spot Teklif Email',
    'CHANGE HISTORY': 'Tarihçe',
    'CONTAINER TYPE': 'Konteynır Tipi',
    'CONSTRUCTION': 'İnşaat',
    'HEAD QUARTERS': 'Genel Merkez',
    'GENERAL_ASSESSMENT': 'Genel Değerlendirme',
    'CONFLICT ON TERMS OF PAYMENT': 'Ödeme Vadesi Uyuşmazlığı',
    'DEFAULT LOCATION': 'Ana Lokasyon',
    'ADMINISTRATIVE AFFAIRS': 'İdari İşler',
    'SATISFACTION_AND_COMPLAINT_MANAGEMENT': 'Memnuniyet ve Şikayet Yönetimi',
    'CUSTOMER CUSTOMS WAREHOUSE': 'Fiktif',
    'SECTOR INFORMATION': 'Sektör Bilgisi',
    'UNITED KINGDOM': 'İngiltere',
    'CUSTOMS INFORMATION': 'Gümrük Bilgisi',
    'NEW DOCUMENT': 'Yeni Belge',
    'KOREA (SOUTH)': 'GÜNEY KORE',
    'COMPETITOR PRICE': 'Rakip Fiyat',
    'MARİNE': 'Deniz',
    'EKOL BONDED WAREHOUSE': 'Ekol Antrepo',
    'DIY STORE (DO-IT-YOURSELF STORE)': 'Yapı Marketleri',
    'IBC CONTAİNER': 'IBC Konteyner',
    'DEFAULT': 'Varsayılan',
    'SINCE THE TAX NUMBER/TAX OFFICE OF THE ACCOUNT COMPANY IS EMPTY/INVALID, THE SPOT QUOTE STATUS CANNOT BE UPDATED!': 'Hesap firmasının vergi numarası/vergi dairesi boş/geçersiz olduğundan spot teklif statüsü güncellenemiyor!',
    'BOOKSTORE': 'Kitapevi',
    'PERSONAL CARE': 'Kişisel Bakım',
    'ACTIVITIES': 'Aktiviteler',
    'DD/MM/YYYY': 'gg/aa/yyyy',
    'QUALITY CONTROL': 'Kalite Kontrol',
    'VIEW': 'Görüntüle',
    'SHORT NAME': 'Kısa Ad',
    'INVOICE TERM': 'Ödeme Vadesi(gün)',
    'SCOPE': 'Kapsam',
    'VEHICLE REQUIREMENTS': 'Araç Gereksinimleri',
    'DAY OF DEPARTURE': 'Çıkış Günü',
    'FROM COUNTRY SHOULD BE {0}.': 'Çıkış ülkesi {0} olmalıdır.',
    'MOTOR CARS/AUTOMOBILE': 'Motorlu Araçlar / Otomobil',
    'CUSTOMS': 'Gümrük',
    'PACKING': 'Ambalaj',
    'PRODUCT DETAILS': 'Ürün Özellikleri',
    'EXHIBITION': 'Fuar',
    'TO COUNTRY': 'Varış Ülkesi',
    'STRUCTURE & DECORATION': 'Yapı & Dekorasyon',
    'RETAIL': 'Perakende',
    'VALIDITY START DATE': 'Geçerlilik Başlangıç Tarihi',
    'WHITE GOODS': 'Beyaz Eşya',
    'PLEASE SELECT TAX OFFICE': 'Lütfen vergi dairesini seçiniz',
    'MEETING': 'Toplantı',
    'BANK TRANSFER': 'Banka Transferi',
    'CUSTOMS LOCATION': 'Gümrük Lokasyonu',
    'ASST. MANAGER': 'Müdür Yardımcısı',
    'SEARCH İN QUADRO': 'QUADRO\'DA ARA',
    'BEVERAGES': 'İçecekler',
    'ACCOUNT OWNER': 'Hesabın Sahibi',
    'CALCULATED LDM': 'Hesaplanan LDM',
    'REOPEN QUOTE': 'Teklifi Yeniden Aç',
    'SERVICE AREA': 'Servis Tipi',
    'PARENT SECTOR': 'Ana Sektör',
    'HARDWARE AND HAND TOOLS': 'Hırdavat & El Aletleri',
    'LOADING TYPE': 'Yükleme Şekli',
    'READY DATE(EAR.)': 'Hazır Tarihi(En Erken)',
    'PHONE NR': 'Numara',
    'POTENTIALS': 'Potansiyeller',
    'PRINTING - PRINTING PRESS': 'Baskı - Matbaa',
    'FREQUENCY TYPE': 'Sıklık Tipi',
    'MANAGER NOTE': 'Yönetici Notu',
    'FOLLOWING FEATURES CAN NOT EXIST TOGETHER: CURTAIN_SIDER - FRIGO\n': 'Aşağıdaki özellikler birlikte bulunamaz: curtaın_sıder - frıgo',
    'MACHINE': 'Makine',
    'LONG TERM': 'Uzun Dönem',
    'LAST UPDATED': 'Son Güncelleme',
    'TIRE RIM / WHEEL RIM': 'Jant',
    'CLEARANCE RESPONSIBLE': 'Gümrükleme Sorumlusu',
    'MANAGER': 'Yönetici',
    'NUMBER': 'Numara',
    'STANDARD': 'Standart',
    'MIN START DATE': 'Min Başlangıç Tarihi',
    'FRIGO GOODS': 'Frigo Yük',
    'HEIGHT': 'Yükseklik',
    'ORGANIC CHEMICALS': 'Organik kimyasallar',
    'RETURN TO COUNTRY OF ORIGINS': 'Mahrece İade',
    'ACTIVITY ': 'Aktivite',
    'RESEARCH & DEVELOPMENT': 'Ar & Ge',
    'BILLING ITEM': 'Fatura Kalemi',
    'FRANCE': 'Fransa',
    'REQUIRED FOR LOADING': 'Yükleme Gereksinimleri',
    'PUBLIC': 'Kamu',
    'CURRENCY': 'Kur',
    'FROM PORT': 'Kalkış Limanı',
    'LOGICTICS': 'Lojistik',
    'ASST. GENERAL MANAGER': 'Genel Müdür Yardımcısı',
    'DISCOUNT AMOUNT': 'İndirim Miktarı',
    'VIDEO CONFERANCE': 'Video Konferans',
    'DOUBLE DECK': 'Çift Katlı Dorse',
    'ELECTRICAL HAND EQUIPMENTS': 'Elektrikli El Aletleri',
    'CANADA': 'KANADA',
    'APPAREL RETAILERS': 'Giyim Perakendecileri',
    'FURNITURE & ACCESSORIES MANUFACTURER': 'Mobilya ve Aksesuar Üreticisi',
    'UNWANTED CUSTOMER': 'İstenmeyen Müşteri',
    'E-COMMERCE (SELL THE SAME TYPE OF PRODUCT)': 'Dikey E-Ticaret Siteleri',
    'QUANTITY': 'Miktar',
    'CONTACT SAVED SUCCESSFULLY': 'Kişi başarıyla kaydedildi',
    'FREQUENCY': 'Sıklık',
    'LOADING LOC.': 'Yükleme Adresi',
    'İNDUSTRY': 'Sanayi',
    'CHANGE HİSTORY': 'Değişiklik Kayıtları',
    'PACKAGE DETAIL': 'Paket Özellikleri',
    'DRAG AND DROP A FILE HERE OR CLICK': 'Bir dosyayı buraya sürükleyip bırakın veya tıklayın',
    'INVOICE DEPARTMENT': 'Fatura Departmanı',
    'READY DATE (LATEST)': 'Hazır Tarihi (En Geç)',
    'SUPPLIER CHAIN': 'Tedarik Zinciri',
    'İTALY': 'İTALYA',
    'XL CERTIFICATE': 'Xl Sertifikalı',
    'MIN CREATION DATE': 'Min Oluşturma Tarihi',
    'GLASS AND CERAMICS': 'Cam ve Seramik',
    'LAST NAME': 'Soyadı',
    'CUSTOMS CLEARANCE PARK': 'Supalan',
    'FREIGHT PRICE': 'Navlun Ücreti',
    'LOGISTIC': 'Lojistik',
    'DEPARTURE': 'Çıkış',
    'PDF CREATED': 'Pdf Oluşturuldu',
    'TOTAL AMOUNTS:': 'Toplam Değerler:',
    'CHAIN STORES': 'Zincir Mağazacılık',
    'LENGTH(CM)': 'Uzunluk(cm)',
    'ADDITIONAL CUSTOMS CLEARANCE COST': 'Ek Gümrükleme Maliyeti',
    'TRUCK INDUSTRY': 'Tır Sanayii',
    'ARMENIA': 'ERMENİSTAN',
    'CONTRACT START DATE': 'Kontrat Başlangıç Tarihi',
    'TOTAL OPEN SPOT QUOTES': 'Toplam Açık Spot Teklifler',
    'CEO': 'CEO',
    'DELIVERY TYPE': 'Teslim Şekli',
    'ACCOUNT TYPE': 'Hesap Tipi',
    'FOOD': 'Gıda',
    'DOMESTİC': 'İç',
    'TASK TYPE': 'Görev Tipi',
    'CREATED AT': 'Oluşturma Zamanı',
    'SALES_QUOTE_OR_CONTRACT_NEGOTIATION': 'Satış Teklif veya Sözleşme Görüşmesi',
    'ASST. GENERAL MANAGER / DIRECTOR': 'Genel Müdür Yardımcısı',
    'GENERAL MANAGER': 'Genel Müdür',
    'SEA': 'Deniz',
    'MYANMAR': 'MYANMAR',
    'ACTIVITY MANAGEMENT': 'Aktivite Yönetimi',
    'POLAND': 'Polonya',
    'MAX CREATION DATE': 'Maks Oluşturma Tarihi',
    'OUR REFERENCE': 'Teklif Numarası',
    'MAX START DATE': 'Maks Başlangıç Tarihi',
    'ALL': 'Tümü',
    'COSMETIC': 'Kozmetik',
    'EARLIEST READY DATE SHOULD NOT BE EMPTY': 'En erken hazır tarihi boş olmamalıdır',
    'LANGUAGE': 'Dil',
    'WİDTH': 'En',
    'MEXICO': 'MEKSİKA',
    'CUSTOMS İNFORMATİON': 'Gümrük Bilgisi',
    'DELIVERY LOC.': 'Teslim Adresi',
    'MAURITANIA': 'MORİTANYA',
    'INDUSTRY': 'Endüstri',
    'EMAIL SENT SUCCESSFULLY.': 'E-posta başarıyla gönderildi.',
    'WHERE EKOL PREFERRED': 'Ekol\'ün Tercih Ettiği Yerde',
    'OWNER SUBSIDIARY': 'Teklif Sahibi Şube',
    'NEW ACTIVITY': 'Yeni Aktivite',
    'ADD_NEW_ACTIVITY': 'Yeni Aktivite Ekle',
    'UPDATE_ACTIVITY': 'Aktiviteyi Güncelle',
    'CREATE_ACTIVITY': 'Aktivite Oluştur',
    'DELETE_ACTIVITY': 'Aktiviteyi Sil',
    'PREPARATION NOTES': 'Hazırlık Notları',
    'FITTING SYSTEMS': 'Bağlantı Elemanları',
    'SPEEDY VAN': 'Speedy Van\n',
    'COPY': 'Kopyala',
    'BELGIUM': 'BELÇİKA',
    'ARE YOU SURE?': 'Emin misiniz ?',
    'CANCEL': 'İptal',
    'SUBMIT': 'Gönder',
    'ENTER_NAME': 'İsminizi Giriniz',
    'FINANCIAL SERVICES': 'Finansal Hizmetler',
    'CUSTOMS CLEARANCE TYPE': 'Gümrükleme Şekli',
    'PETROL PRODUCTS': 'Petrol Ürünleri',
    'NO ACTIVITY': 'Aktivite yok',
    'PACKAGE DETAILS': 'Paket Özellikleri',
    'COSMOSHOP': 'Cosmoshop',
    'MİN UPDATE DATE': 'Min Güncelleme Tarihi',
    'LENGTH': 'Uzunluk',
    'TOTAL ACTİVİTİES': 'Toplam Aktiviteler',
    'RETURN TO MAİN PAGE': 'ANASAYFAYA DÖN',
    'CANCELED BY CUSTOMER': 'Müşteri Tarafından İptal Edildi',
    'CALCULATE': 'HESAPLA',
    'OVERSIZE GOODS': 'Gabari Dışı Yük',
    'NO SPECIAL VEHICLE AND EQUIPMENT (DOUBLE DECKER)': 'Özel Araç ve Ekipman Yok (Çift Katlı)',
    'HUMAN RESOURCES': 'İnsan Kaynakları',
    'FOOD PRODUCT': 'Gıda Ürünü ',
    'SUPERVISOR': 'Şef',
    'TO POSTAL': 'Varış Posta Kodu',
    'SALES MANAGER': 'Satış Yöneticisi',
    'DİY STORE (DO-İT-YOURSELF STORE )': 'El İşi Mağazası',
    'WIDTH(CM)': 'En(cm)',
    'SPOT QUOTE CLOSURE INFO': 'Spot Teklif Kapatma Bilgisi',
    'MEDICAL SUPPLIES': 'Tıbbi Malzemeler',
    'FISCAL CUSTOMS': 'Fiskal Gümrük',
    'TOOL': 'Araç',
    'CONTAINER': 'Konteyner',
    'CONTRACT END DATE': 'Kontrat Bitiş Tarihi',
    'LOADING METER (LDM)': 'Ldm',
    'CASH': 'Nakit',
    'PRICES': 'Fiyatlar',
    'MARK AS CANCELED': 'Teklifi İptal Et',
    'PARAMETERS AFFECTING PRICE HAVE CHANGED, PLEASE PRESS CALCULATE BUTTON FOR RECALCULATION.': 'Fiyatı etkileyen parametreler değişti, yeniden hesaplama için lütfen hesapla butonuna basın.',
    'BILLNG ITEM': 'Fatura Kalemi',
    'MAX_AMOUNT': 'MAKSİMUM MİKTAR',
    'CHANGE TIME': 'Değiştirme Zamanı',
    'UPLOAD': 'Yükle',
    'APPAREL MANUFACTURERS': 'Hazır Giyim Üreticileri',
    'CUSTOMS OFFICE': 'Gümrük Ofisi',
    'CHEMICAL SUBSTANCES': 'Kimyasal maddeler',
    'TAX İD': 'Vergi Numarası',
    'COUNSELING': 'Rehberlik',
    'NEW ACCOUNT': 'Yeni Hesap',
    'NOTES': 'Notlar',
    'IS DEFAULT': 'Varsayılan',
    'EDUCATION': 'Eğitim',
    'SET AS DEFAULT': 'Varsayılan Olarak Belirle',
    'CODE': 'Kod',
    'TOTAL ACTIVITIES': 'Toplam Aktiviteler',
    'QUOTE NUMBER': 'Teklif Numarası',
    'NORTH CYPRUS TURKISH REPUBLIC': 'KUZEY KIBRIS TÜRK CUMHURİYETİ',
    'CONTENT': 'İçerik',
    'PER SHIPMENT': 'yük başı',
    'STACKABILITY': 'İstifleme',
    'SHIPMENT LOADING TYPE': 'FTL/LTL',
    'MADAGASCAR': 'MADAGASKAR',
    'EMAILS': 'Email',
    'AREA CODE': 'Kod ',
    'START': 'BAŞLA',
    'FOOD  - FRESH / DAILY FOOD ': 'Gıda- Taze &  Günlük Tüketim Ürünleri',
    'QUOTES': 'Teklifler',
    'DELIVERY ADDRESS': 'Teslim Adresi',
    'FROM COUNTRY': 'Çıkış Ülkesi',
    'CHEMISTRY': 'Kimya',
    'AT COUNTRY BORDER CUSTOMS': 'Ülke Sınır Gümrüğünde',
    'CANCELED': 'İptal Edildi',
    'BOUNDED WAREHOUSE': 'Antrepo',
    'PLEASE SAVE THE LOCATION YOU ARE EDITING': 'Lütfen düzenlediğiniz lokasyonu kaydediniz',
    'WEEKLY': 'Haftalık',
    'BUILDING MATERIAL PRODUCER': 'Yapı Malzemesi Üreticisi',
    'FAILURE TO OBSERVE THE DEADLINE DATE': 'Son Dönüş Tarihine Uyulmaması',
    'MEDICATION': 'İlaç',
    'PLEASE SELECT STACKABILITY': 'Lütfen istif bilgisi seçiniz',
    'READY DATE(LT.)': 'Hazır Tarihi(En Geç)',
    'CHAIRMAN': 'Yönetim Kurulu Başkanı',
    'REQUIRED FOR UNLOADING': 'Boşaltma Gereksinimleri',
    'MARINE': 'Deniz',
    'OFFICE MACHINE': 'Büro Makinesi',
    'COMPANY CONTACTS': 'Firma Yetkilileri',
    'TAIL LIFT': 'Asansörlü Araç',
    'NO SPECIAL VEHICLE AND EQUIPMENT (HEAT CONTROL)': 'Özel Araç ve Ekipman Yok (Isı Kontrolü)',
    'UPDATE IS NOT ALLOWED.': 'Güncellemeye izin verilmiyor.',
    'SR. SUPERVISOR': 'Kıdemli Şef',
    'STORAGE': 'Depolama',
    'SERVICE TYPE': 'Servis Tipi',
    'ABROAD': 'Yurtdışı',
    'DANGEROUS GOODS(IMO)': 'Tehlikeli Yük(IMO)',
    'TAX ID': 'Vergi Numarası',
    'EXTERNAL UNLOADING COST': 'Harici Boşaltma Maliyeti',
    'TRANSIT TRADE': 'Transit Ticaret',
    'INVOICE LOCATION': 'Fatura Lokasyonu',
    'INCOTERM': 'Incoterm',
    'VIEW PDF': 'PDF\'i Görüntüle',
    'PIECE': 'Parça',
    'ARRIVAL CUSTOMS COST PRICE': 'Varış Gümrükleme Ücreti',
    'BARREL': 'Varil',
    'ACTIVITY': 'Aktivite',
    'GERMANY': 'Almanya',
    'PLEASE SELECT PARENT SECTOR': 'Lütfen ana sektör seçiniz',
    'ASST. GENERAL MANAGER / DİRECTOR': 'Genel Müdür Yardımcısı',
    'STRATEGIC INFORMATION': 'Stratejik Bilgi',
    'CUSTOMER ADDRESS': 'Müşteri Adresi',
    'CHINA': 'ÇİN',
    'PARTIAL WON': 'Kısmi Kazanıldı',
    'FOLLOWING FEATURES CAN NOT EXIST TOGETHER:': 'Bu özellikler birlikte bulunamaz:',
    'HOME CARE PRODUCTS': 'Ev Bakım Ürünleri ( Home Care )',
    'NEXT PAGE': 'SONRAKİ ',
    'COST STUDY OF COMPANY': 'Şirketin Maliyet Çalışması',
    'MARTINIQUE': 'MARTİNİQUE',
    'PAYMENT DUE DAYS': 'Ödeme Vadesi',
    'CAD-CASH AGAİNST DOCUMENTS': 'CAD - Vesaik Mukabili Ödeme',
    'ACCOUNT LOCATION': 'Hesap Lokasyonu',
    'MALAWI': 'MALAWİ',
    'NAURU': 'NAURU',
    'ANNUAL': 'Yıllık',
    'QUADRO QUOTE NUMBER': 'Quadro Teklif Numarası',
    'OTHER': 'Diğer',
    'PRODUCTION': 'Üretim',
    'TRAİLER': 'Treyler',
    'CLOSED': 'Kapatıldı',
    'VALIDITY END DATE': 'Geçerlilik Bitiş Tarihi',
    'NO DATA TO DISPLAY': 'Gösterilecek bilgi yok',
    'TOTAL AMOUNTS': 'Toplam Değerler',
    'POTENTIAL': 'Potansiyel',
    'SEARCH FOR COMPANY...': 'Firma ara...',
    'DISCOUNT RATE': 'İndirim Oranı',
    'RAILWAY': 'Demiryolu',
    'COPY QUOTE': 'Teklifi Kopyala',
    'NO SPECIAL VEHICLE AND EQUIPMENT (SIOBAS)': 'Özel Araç ve Ekipman Yok (Silobas)',
    'SERVICE': 'Hizmet',
    'PROSPECT': 'Muhtemel Müşteri',
    'LIBERIA': 'LİBERYA',
    'AFTER MARKET': 'After Market (yedek parça)',
    'LOGİSTİCS': 'Lojistik',
    'COMPANY INFO': 'Firma Bilgisi',
    'DELIVERY COST': 'Teslimat Ücreti',
    'DOWNLOAD TEMPLATE': 'Şablonu İndir',
    'SUB SECTOR': 'Alt Sektör',
    'AUTOMOTİVE': 'Otomotiv',
    'CREATE CONTACT': 'Yetkili Oluştur',
    'PRODUCT DETAIL ': 'Ürün Özelliği',
    'SEND': 'GÖNDER',
    'TOTAL LOGİSTİCS POTENTİAL': 'Toplam Lojistik Potansiyeli',
    'FROM POSTAL': 'Çıkış Posta Kodu',
    'PRODUCT_INTRODUCTION': 'Ürün Tanıtımı',
    'NEW CONTACT': 'Yeni Yetkili',
    'BATTERY / ACCUMULATOR': 'Pil / Akümülatör',
    'ACTIVITY REPORT': 'Faaliyet Raporu',
    'COMMERCIAL VEHICLE (LIGHT/HEAVY)': 'Ticari Araç (Hafif / Ağır)',
    'CALL': 'Arama',
    'TAX OFFICE': 'Vergi Dairesi',
    'TOTAL': 'Toplam',
    'SEARCH İN ONEORDER': 'OneOrder\'da Ara',
    'ADD NEW ': 'Yeni Ekle',
    'ARRİVAL CUSTOMS COST': 'Varış Gümrükleme Ücreti',
    'TEXTILE RAW MATERIALS': 'Tekstil Hammaddeleri',
    'INCOMES': 'Gelirler',
    'MACAU': 'MACAU',
    'READY DATE (EARLIEST)': 'Hazır Tarihi (En Erken)',
    'WHERE CUSTOMER PREFERRED': 'Müşterinin Tercih Ettiği Yerde',
    'AGENCY COMMISSION COST': 'Acente Komisyon Ücreti',
    'QUOTE SAVED SUCCESSFULLY': 'Teklif başarıyla kaydedildi',
    'CONTAINER TYPES': 'Konteynır Tipi',
    'İNTERNAL': 'İç',
    'LIGHT LOAD': 'Hafif Yük',
    'ARRIVAL CUSTOMS COST': 'Varış Gümrükleme Ücreti',
    'FMCG': 'Hızlı Tüketim Malları',
    'TO PORT': 'Varış Limanı',
    'ACCOUNT SEARCH': 'Hesap Arama',


    // CALENDAR
    'January': 'Ocak',
    'February': 'Şubat',
    'March': 'Mart',
    'April': 'Nisan',
    'May': 'Mayıs',
    'June': 'Haziran',
    'July': 'Temmuz',
    'August': 'Ağustos',
    'September': 'Eylül',
    'October': 'Ekim',
    'November': 'Kasım',
    'December': 'Aralık',
    'Add_New_Event': 'Yeni Etkinlik Ekle',
    'Update_Event': 'Etkinliği Güncelle',
    'UPDATE': 'Güncelle',
    'Event_Type': 'Etkinlik Türü Seçiniz',
    'Activity_Type': 'Aktivite Türü Seçiniz',
    'SHARE_WITH_ALL_PARTICIPANTS': 'Tüm Katılımcılarla Paylaş',
    'Header': 'Başlık',
    'Scope': 'Kapsam Seçiniz',
    'Tool': 'Araç Seçiniz',
    'Location': 'Lokasyon',
    'Description': 'Açıklama',
    'Select_Segment': 'Segment Seçiniz',
    'more': 'daha fazla',
    'Segment_not_found': 'Segment Bulunamadı!',
    'Provide_header': 'Başlık giriniz',
    'Provide_event_type': 'Etkinlik tipi seçiniz',
    'Provide_activity_type': 'Etkinlik tipi seçiniz',
    'Provide_segment_type': 'Segment tipi seçiniz',
    'Provide_scope_type': 'Kapsam tipi seçiniz',
    'Provide_tool_type': 'Araç tipi seçiniz',
    'Provide_location': 'Lokasyon belirtiniz',
    'PROVIDE_GENDER': 'Cinsiyet belirtiniz',
    'PROVIDE_TITLE': 'Ünvan belirtiniz',
    'PROVIDE_NAME': 'İsim belirtiniz',
    'PROVIDE_SURNAME': 'Soyisim belirtiniz',
    'PROVIDE_DEPARTMENT': 'Departman belirtiniz',
    'Provide_participant': 'Katılımcı(lar) belirtiniz',
    'Provide_account': 'Hesap belirtiniz',
    'Correct_Date': 'Etkinlik başlangıç tarihi bitiş tarihinden önce olmalıdır',
    'Provide_description': 'Açıklama giriniz',
    'EVENT': 'Etkinlik',
    'SEE_ACTIVITY': 'Aktiviteyi Gör',
    'UPDATE_EVENT': 'Etkinliği Güncelle',
    'DELETE_EVENT': 'Etkinliği Sil',
    'ACTIVITY_UPDATE_ERROR': 'Aktiviteyi güncellemek için gerekli bilgileri doldurunuz',
    'ACTIVITY_DELETE_SUCCESS': 'Silme işleminiz başarıyla gerçekleştirilmiştir',
    'ACTIVITY_UPDATE_SUCCESS': 'Güncelleme işleminiz başarıyla gerçekleştirilmiştir',
    'ACTIVITY_CREATE_SUCCESS': 'Aktivite oluşturma işleminiz başarıyla gerçekleştirilmiştir',
    'ACTIVITY_CREATE_ERROR': 'Yeni bir aktivite oluşturmak için gerekli bilgileri doldurunuz',
    'ACTIVITY_CREATE_ERROR2': 'Aktivite oluşturulurken hata oluştu.',
    'ACTIVITY_UPDATE_ERROR2': 'Aktivite güncellenirken hata oluştu.',


    'EXPENSE_ORDER': 'Masraf Girilmiş Sipariş',
    'PROBLEMATIC_ORDER': 'Problemli Sipariş',
    'EXPENSE_COMPANY': 'Masrafı Yapan Şirket',
    'MALE': 'Erkek',
    'FEMALE': 'Kadın',
    'COUNTRY_CODE': 'Ülke Kodu',
    'REGION_CODE': 'Bölge Kodu',
    'CREATE_CONTACT_SUCCESS_MESSAGE': 'Yetkili başarıyla oluşturuldu.',
    'CREATE_CONTACT_ERROR_MESSAGE': 'Yetkili oluşturulurken bir hata oluştu.',
    'EDIT_CONTACT_SUCCESS_MESSAGE': 'Yetkili başarıyla düzenlendi.',
    'EDIT_CONTACT_ERROR_MESSAGE': 'Yetkili düzenlenirken hata oluştu',

    'ALL_ORDERS': 'Tüm Siparişler',
    'COMPLAINTS': 'Şikayetler',
    'COMPLAINT_TYPE': 'Şikayet Tipi',
    'UPDATE_COMPLAINT': 'Şikayet Güncelle',
    'COMPLAINT_DUE_DATE': 'Çözülmesi Gereken Tarih',
    'COMPLAINT_SUBJECT': 'Şikayet Konusu',
    'Add_New_Complaint': 'Yeni Şikayet Ekle',
    'Update_New_Complaint': 'Şikayeti Güncelle',
    'Provide_customer': 'Müşteri Belirtiniz',
    'Provide_complaint_type': 'Şikayet türü belirtiniz',
    'DESCRIPTION': 'Açıklama',
    'VIDEO_CONFERENCE': 'Video Konferans',
    'E MAIL': 'E-mail',
    'FAIR': 'Fuar',
    'COLLECTION_MEETING': 'Tahsilat Toplantısı',
    'LTL_CUSTOMER_ACQUISITION': 'LTL Müşteri Kazanımı',
    'COMPLAINT_NO': 'Şikayet Numarası',
    'COMPLAINT_CREATED_SUCCESSFULLY': 'Şikayet başarıyla oluşturuldu.',
    'COMPLAINT_EDITED_SUCCESSFULLY': 'Şikayet başarıyla düzenlendi.',
    'NEW_COMPLAINT': 'Yeni Şikayet',
    'OTHERS': 'Diğer',
    'LOADING WAS DELAYED': 'Yükleme Gecikmesi',
    'DELETE_CONTACT_DIALOG_MESSAGE': 'Seçilen yetkili silinecektir. Devam etmek istediğinize emin misiniz?',
    'DELETE_ACTIVITY_DIALOG_MESSAGE': 'Seçilen aktivite silinecektir. Devam etmek istediğinize emin misiniz?',
    'YES': 'Evet',
    'DELETE_CONTACT_SUCCESS_MESSAGE': 'Seçilen yetkili başarıyla silinmiştir',
    'DELETE_EVENT_SUCCESS_MESSAGE': 'Seçilen etkinlik başarıyla silinmiştir',
    'DELETE_ACTIVITY_ERROR_MESSAGE': 'Seçilen aktivite silinirken bir hata oluştu',
    'DAMAGE': 'Hasar',
    'MISSING': 'Kayıp',
    'COMPLAINT_STATUS': 'Şikayet Durumu',
    'SOLVED': 'Çözüldü',
    'NOT_SOLVED': 'Çözülmedi',
    'SOLVE_COMPLAINT': 'Şikayeti Çöz',
    'SOLVED_COMPLAINT_DESCRIPTION': 'Çözülen Şikayet Açıklaması',
    'BUSINESS_AREA': 'İş Alanı',
    'DEBIT_TOTAL': 'Toplam Borç',
    'DUE_EXPIRED_AMOUNT': 'Vadesi Geciken Tutar',
    'DUE_WAITING_AMOUNT': 'Vadesi Bekleyen Tutar',
    'ORDER_NOT_FOUND': 'Sipariş bulunamadı',
    'ORDER_CODE_REQUIRED': 'Sipariş Numarası giriniz.',
    'PROFILE': 'Profil',
    'LOG_OUT': 'Çıkış yap',
    'Activity can not be deleted.': 'Activity can not be deleted.',
    'OPPORTUNITIES': 'Fırsatlar',
    'OPPORTUNITY_SUBJECT': 'Konu',
    'ADD_NEW_OPPORTUNITY': 'Yeni Ekle',
    'OPPORTUNITY_CREATE_DATE': 'Oluştulma Tarihi',
    'OPPORTUNITY_DUE_DATE': 'Sona Erme Tarihi',
    'UPDATE_OPPORTUNITY': 'Güncelle',
    'ORDER_DETAIL': 'Sipariş Detayı',
    'UPDATE_APP': 'Uygulamayı Güncelle',
    'SELECTED_USER': 'Seçili Kullanıcı',
    'TIME_PERIOD': 'Zaman Aralığı',
    'SELECT_PERIOD': 'Aralık Seçiniz',
    'LAST_ONE_MONTH': 'Son Bir Ay',
    'LAST_TWO_MONTHS': 'Son İki Ay',
    'LAST_THREE_MONTHS': 'Son Üç Ay',
    'LAST_FOUR_MONTHS': 'Son Dört Ay',
    'LAST_FIVE_MONTHS': 'Son Beş Ay',
    'LAST_SIX_MONTHS': 'Son Altı Ay',
    'LAST_YEAR': 'Son Bir Yıl',
    'LAST_TWO_YEARS': 'Son İki Yıl',
    'LAST_THREE_YEARS': 'Son Üç Yıl',
    'ALL_TIME': 'Tüm Zamanlar',
    'NO': 'No',
    'CUSTOMER_NAME': 'Müşteri Adı',
    'TO_DO': 'Yapılacaklar',
    'COMPLAINT_SEARCH_INFO': 'Müşteri adı, Şikayet Tipi, Şikayet Konusu ile arama yapabilirsiniz',
    'ORDER_SEARCH_INFO': 'Sipariş No ve Müşteri adı ile arama yapabilirsiniz.',
    'SEARCH_BY_SUBJECT': 'Konu ile Arama yapabilirsiniz',
    'DEADLINE': 'Tamamlanması Gereken Tarih',
    'ORDERS_DEPARTED_FROM_TERMINAL': 'Terminalden Yola Çıkan Siparişler',
    'LOADING': 'Yükleniyor',
    'ACTIVITY_ERROR': 'Tıkladığınız aktiviteyle ilgili bir problem oluştu',
    'ACTIVITY_DELETE_ERROR': 'Seçilen aktivite silinemez',
    'NO_INTERNAL_PARTICIPANT': 'İç Katılımcı Bulunamadı!',
    'SELECT_INTERNAL_PARTICIPANT': 'İç Katılımcı Seçiniz',
    'NO_EXTERNAL_PARTICIPANT': 'Dış Katılımcı Bulunamadı!',
    'SELECT_EXTERNAL_PARTICIPANT': 'Dış Katılımcı Seçiniz',
    'SELECT_ACCOUNT': 'Hesap Seçiniz',
    'SELECT_USER': 'Kullanıcı Seçiniz',
    'NO_ACCOUNT_FOUND': 'Hesap Bulunamadı!',
    'NO_USER_FOUND': 'Kullanıcı Bulunamadı!',
    'NO_ACCOUNT_OWNER_FOUND': 'Hesap Sahibi Bulunamadı!!',
    'SELECT_ACCOUNT_OWNER': 'Hesap Sahibi Seçiniz',
    'RECORD_DELETE_SUCCESS': 'Kayıt başarıyla silindi.',
    'RECORD_CREATE_SUCCESS': 'Kayıt başarıyla oluşturuldu.',
    'RECORD_EDIT_SUCCESS': 'Kayıt başarıyla düzenlendi.',
    '404_ERROR': '404 Sayfa Bulunamadı',
    'PAGE_NOT_FOUND_ERROR': 'Aradığınız sayfa bulunmamaktadır',
    'TAKE_ME_HOME': 'Ana sayfaya git',
    'ACCOUNTS_NOT_FOUND_WARNING': 'Bu hesaba bağlı müşteri bulunamadı.',
    'PROBLEM_DETAIL': 'Problem Detayı',
    'ACTIVE': 'AKTİF',
    'Active': 'AKTİF',
    'PASSIVE': 'PASİF',
    'Passive': 'PASİF',
    'AKTIF': 'AKTİF',
    'Aktif': 'AKTİF',
    'PASIF': 'PASİF',
    'Pasif': 'PASİF',
    'SEARCH_INPUT_PLACE_HOLDER': 'Arama',
    'CREATE_DATE': 'Oluşturulma Tarihi',
    'NOTIFICATIONS': 'Bildirimler',
    'MARK_ALL_AS_READ': 'Hepsini Okundu Olarak İşaretle',
    'VIEW_NOTIFICATIONS': 'Tüm Bildirimleri Görüntüle',
    'NO_NOTIFICATIONS': 'Hiç bildiriminiz yok.',
    'DOCUMENTS_ON_PORTEKOL': 'Portekol üzerinde yer alan güncel dokümanlara <a target="_blank" href="https://drive.google.com/drive/folders/1bDr75WXF9KsxFXOsBTi9XfNE52QMZKYI">link</a> üzerinden erişebilirsiniz.',
    'REQUIRED': 'Doldurulması zorunlu',
    'TODAY': 'Bugün',
    '3_OR_MORE_CHARS': 'Lütfen en az 3 karakter giriniz',
    'ATTACHMENTS': 'Ekler',
    'ATTACHMENT': 'Ek',

};
